# Generated by Django 2.2.28 on 2023-04-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230410_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='profesor_id',
            new_name='profesor',
        ),
    ]
