# Generated by Django 2.2.28 on 2023-04-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230410_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
        migrations.AddField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(related_name='profesores', to='myapp.Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_dictados', to='myapp.Profesor'),
        ),
    ]
