# Generated by Django 2.2.28 on 2023-04-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230425_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='cuit',
            field=models.CharField(default=123456789, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default='ejemplo@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(default=111111111, max_length=15),
            preserve_default=False,
        ),
    ]
